main: xbeastmode\antispammer\AntiSpammer
api: 2.0.0
load: STARTUP
name: AntiSpam
description: "antispam plugin"
version: 1.2
author: xBeastMode

permissions:
  spam.bypass:
    default: op
    description: "Allow bypassing the spam limit"
